name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend
        working-directory: backend-java
        run: ./mvnw clean package

      - name: Run backend tests
        working-directory: backend-java
        run: ./mvnw test

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: frontend-js
        run: npm install

      - name: Run frontend tests
        working-directory: frontend-js
        run: npm test

  build-cpp-stub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      - name: Build C++ stub
        working-directory: simulation-cpp/stub_server
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

